import SWRProvider from "@/components/SWRProvider";
import { GQL_GET_TODO_LIST } from "@/response/responses";
import fetchGraphQL from "@/server/fetchGraphQL";
import React from "react";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
  const fallback: Record<string, any> = {};
  for (const { key, data } of Promise.all([
    fetchGraphQL({ query: GQL_GET_TODO_LIST }),
  ])) {
    fallback[key] = data;
  }

  return (
    <html lang="en">
      <body>
        <SWRProvider fallback={fallback}>{children}</SWRProvider>
      </body>
    </html>
  );
}
